services:
  db:
    image: 'mariadb:11.3.2'
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'dev'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
      MYSQL_ROOT_PASSWORD: 'dev'
      MARIADB_AUTO_UPGRADE: '1'
      MARIADB_INITDB_SKIP_TZINFO: '1'
    ports:
      - '3306:3306'
    command: --max-connections=2000

  db-test:
    image: 'mariadb:11.3.2'
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
      MARIADB_AUTO_UPGRADE: '1'
      MARIADB_INITDB_SKIP_TZINFO: '1'
    ports:
      - '3307:3306'
    tmpfs:
      - /var/lib/mysql
    command: --max-connections=2000

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
      redis-sdlog:
        condition: service_started
    volumes:
      - .:/app
    working_dir: /app
    command: 'pnpm debug'
    ports:
      - '3000:3000' # Server Application
      - '9229:9229' # NodeJS Debug
    env_file:
      - .env.local

  redis-sdlog:
    image: 'redis'
    ports:
      - '6379:6379'